### ISSUE TITLE
Some enhancements

### ISSUE THREAD

**Issue by thany** [vitaliymaz/vscode-svg-previewer#14]
I think this extension needs some love, and there are a few things I'm missing:

- Auto open the preview when opening an SVG
- Right-click to zoom out
- A button to zoom back to 100%, and one to fill the panel
- Remove the view source button, since it opens the source that's already there on the left. Alternatively, make it focus the source code.
- A picker for the background colour/pattern

**Comment by vitaliymaz** [comment]
Good points, @thany. Thank you for the feedback. I am currently working on the update which will bring many improvements, so many of your suggestions will be resolved.

- Auto open the preview when opening an SVG - _Good Suggestion_
- Right-click to zoom out - _After the next update you will have a toolbar with zoom buttons. The mouse wheel will be an option as well_
- A button to zoom back to 100%, and one to fill the panel - _First one will be in the toolbar, will think on the second one_
- Remove the view source button, since it opens the source that's already there on the left. Alternatively, make it focus the source code. - _the behavior was copied from the Markdown built-in plugin, need to investigate more this question_
- A picker for the background colour/pattern - _The toolbar will have buttons to switch light/dark background pattern_

So, leaving your task open for now, and after the next update in few days, I will extract some separate tasks from your suggestions.

**Comment by vitaliymaz** [comment]
@thany, could you update the plugin and try it now? It has significant improvements.

**Comment by thany** [comment]
Hey much better! 🙋‍♂️

Can you change the zoom buttons so they can be held down to keep zooming? I feel that's the one little thing I'm missing atm. It's probably because the amount by which it zooms is quite small. I'm not 100% sure that this is a good idea though. Up to you 😀

**Comment by vitaliymaz** [comment]
I think I will just make zoom buttons more sensitive.

**Comment by bytelabsco** [comment]
I would like to throw my support behind having the preview pane open automatically (or at least an option to enable that behavior)

**Comment by vitaliymaz** [comment]
@bytelabsco, already in progress. I will add a setting to switch on automatic opening.

**Comment by vitaliymaz** [comment]
@bytelabsco, a new version was just pushed. You will have a setting to switch on automatic opening. By default it is disabled.
